server:
  port: 8881
  servlet:
    context-path: /api

# 连接mysql 数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:3306/networkdisk?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true&remarks=true&useInformationSchema=true
    username: 
    password: 

#mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      # 配置实体类所对应的表的统一前缀
      table-prefix: nwd_
      # 配置统一的主键生成策略
      id-type: assign_id
  configuration:
    log_impl: org.apache.ibatis.logging.stdout.StdOutImpl
